name: "build"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Get package name and version
        id: cargo_version
        run: |
          echo "NAME=$(grep '^name' Cargo.toml | sed -E 's/name = \"(.*)\"/\1/')" >> $GITHUB_ENV
          echo "VERSION=$(grep '^version' Cargo.toml | sed -E 's/version = \"(.*)\"/\1/')" >> $GITHUB_ENV

      - name: Build with wasm-pack
        run: wasm-pack build --release --target nodejs

      - name: Rename Wasm file with version
        run: |
          mkdir -p dist
          mv pkg/${{ env.NAME }}_bg.wasm pkg/${{ env.NAME }}_${{ env.VERSION }}.wasm

      - name: Upload Wasm file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.NAME }}_${{ env.VERSION }}.wasm
          path: pkg/${{ env.NAME }}_${{ env.VERSION }}.wasm
          overwrite: false